on:
  release:
    types: [created]
  push:
    branches: [ main ]
  workflow_run:
    workflows: 
      - configure github runner in eks
    types:
      - completed

name: Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
