name: configure github runner in eks
on:
  push:
    branches:
      - main
env:
  BUILD_NUMBER: ${{ github.run_number }}
  GH_SHA: ${{ github.sha }}
  GH_BRANCH: ${{ github.ref_name }}
  GH_OWNER: shadabshah1680
  GH_REPO_NAME: Lambda_Code
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  OIDC_ROLE_ARN: ${{ secrets.OIDC_IAM_ROLE }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  ANSIBLE_BRANCH: main
permissions:
      id-token: write 
      contents: read

jobs:
  SetupEKS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.OIDC_IAM_ROLE }}
        role-session-name: ${{ github.sha }} 
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: setup kube config
      run: |
        make eks
        kubectl get nodes
        echo $GITHUB_REPOSITORY
        sed -i "s|testrepo|${GITHUB_REPOSITORY}|g" runner.yaml
        cat runner.yaml
        kubectl apply -f runner.yaml
  EKSGihubRunner:
    runs-on: self-hosted
    needs: SetupEKS
    steps:
    - name: setup kube config
      run: |
        echo "tested" 
        echo "maaz"
  DeleteRunner:
    runs-on: ubuntu-latest
    needs: EKSGihubRunner
    steps:
    - uses: actions/checkout@v3
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.OIDC_IAM_ROLE }}
        role-session-name: ${{ github.sha }} 
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: setup kube config
      run: |
        make eks
        kubectl get nodes
        echo $GITHUB_REPOSITORY
        sed -i "s|testrepo|${GITHUB_REPOSITORY}|g" runner.yaml
        cat runner.yaml
        kubectl delete -f runner.yaml